version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    image: rails_template:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      CAPYBARA_SERVER_HOST: web
      CAPYBARA_APP_HOST: http://web
    depends_on:
      - db

  selenium_chrome:
    image: selenium/standalone-chrome-debug

  adminer:
    image: adminer
    ports:
      - "8080:8080"
  js:
    image: rails_template:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
  css:
    image: rails_template:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true


volumes:
  db:
  bundle:
  node_modules:
